# Generated by Django 5.1.1 on 2025-04-03 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_table.department')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_table.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=20)),
                ('time', models.CharField(choices=[('9:00-9:55 AM', '9:00-9:55 AM'), ('10:00-10:55 AM', '10:00-10:55 AM'), ('11:00-11:55 AM', '11:00-11:55 AM'), ('12:00-12:55 PM', '12:00-12:55 PM'), ('2:00-2:55 PM', '2:00-2:55 PM'), ('3:00-3:55 PM', '3:00-3:55 PM')], max_length=20)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_table.department')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_table.room')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_table.subject')),
            ],
        ),
    ]
