# Generated by Django 5.1.1 on 2025-04-04 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_table', '0002_remove_subject_department_remove_schedule_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_number',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='department',
        ),
        migrations.AddField(
            model_name='room',
            name='department',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timetableslot',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='time_table.course'),
        ),
        migrations.AlterField(
            model_name='timetableslot',
            name='day',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='timetableslot',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='time_table.room'),
        ),
        migrations.AlterField(
            model_name='timetableslot',
            name='time_slot',
            field=models.CharField(max_length=20),
        ),
    ]
