# Generated by Django 5.1.1 on 2025-04-04 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_table', '0003_remove_room_room_number_remove_teacher_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='department',
            field=models.CharField(default='Computer Science', max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.CharField(max_length=10),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='time_table.department'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_table.department'),
        ),
    ]
