# Generated by Django 5.1.1 on 2025-04-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_table', '0007_alter_teacher_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='max_lectures',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
